### ISSUE TITLE
root/rooKey option

### ISSUE THREAD

**Issue by Yomguithereal** [bfitch/cachejax#2]
Hello @bfitch. I feel like you could simplify you API by making the `root` option a bit more polymorphic. What I mean by that is that the mere existence of a string in the `root` option could assess for its need.

**Comment by bfitch** [comment]
Yeah, great suggestion. So just have `root: String`, then check the string value for the root name, if none provided, use `path` as the root name.

But, if you only have a string, how would you indicate the endpoint returns no root, ie `{id:  1, name: 'bob', ...}`? I guess that was the idea behind separating `root` and `rootKey`. Did I understand you correctly? :smile:

**Comment by bfitch** [comment]
@Yomguithereal I see what you're saying now. Sorry.
- have `root` default to `true`
- accept `root: true|false` or `root: 'string'`
- if `string` set the root name, otherwise use the `path` as the root name

Will definitely implement. Thanks!

**Comment by bfitch** [comment]
@Yomguithereal this is implemented in the new release `0.1.0`.

`rootKey` is gone and you can now pass in `{root: true || false}` or the name as a string `{root: 'myCoolUser'}`. `root` defaults to `true`.

Thanks for the suggestion! :smile:

**Comment by Yomguithereal** [comment]
Cool! Will read your README once more and tell you whether I find other things :smile:

**Comment by bfitch** [comment]
That would be excellent. Thanks for the feedback.
